# This file was generated by the {rix} R package v0.18.5 on 2026-09-04
# with following call:
# >rix(r_ver = "4.6.1",
#  > r_pkgs = c("ellmer",
#  > "shinychat",
#  > "shiny",
#  > "devtools",
#  > "shinytest2",
#  > "bslib",
#  > "testthat",
#  > "reactable",
#  > "watcher"),
#  > ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
  pkgs = import (fetchTarball {
    url = "https://github.com/rstats-on-nix/nixpkgs/archive/2026-08-24.tar.gz";
    sha256 = "13xkcmz9ixcgymkfal299fcm27jjmqrw17cclyc5dkn9wflkvw4v";
  }) {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      bslib
      devtools
      ellmer
      reactable
      shiny
      shinychat
      shinytest2
      testthat
      watcher;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.isx86_64 && pkgs.stdenv.isLinux then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = pkgs.lib.flatten [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
